### ISSUE TITLE
[BUG] Regex file apostrophe rules not recognized

### ISSUE THREAD

**Issue by ChiboYen** [OpticFusion1/ChatBot#4]
**Describe the bug**
Here is my regex config:
```
what's: you said what
don't: you said dont
```

The problem is that the bot doesn't recognize me saying what's and don't because they have an apostrophe.

**To Reproduce**
1. Use an apostrophe(s) in regex config
2. Say what should match the rule

**Expected behavior**
The expected programmed response

**Screenshots**
![image](https://user-images.githubusercontent.com/69435677/105819214-2286bd00-5f75-11eb-8eb7-71673371b4cf.png)

**Comment by OpticFusion1** [comment]
Ugh, dealing with punctuation is fun.
I'll have a second look at this mess

**Comment by OpticFusion1** [comment]
Next update will fix this (Hopefully not breaking something else in the process)
