### ISSUE TITLE
[BUG] Bot does not differentiate between capital single letters like I

### ISSUE THREAD

**Issue by ChiboYen** [OpticFusion1/ChatBot#7]
**Describe the bug**
`(how|hwo) (do i|to) (u|you|get|obtain) diamonds` is set to the regex list
If you say "how do i get diamonds" it matches
If you say "how do I get diamonds" it doesn't

I shouldn't be case sensitive, should it? If I am misunderstanding regex or doing something wrong, let me know!

**Comment by OpticFusion1** [comment]
Try
(?i)(how|hwo) (do i|to) (u|you|get|obtain) diamonds

**Comment by ChiboYen** [comment]
Fixed, problem was my lack of Regex knowledge, thanks!
